set_property SRC_FILE_INFO {cfile:D:/Zynq/youlaoshi_first/net9_clkdiv/programmer_ledflash/led_flash/led_flash.srcs/constrs_1/new/led_stream.xdc rfile:../../../led_flash.srcs/constrs_1/new/led_stream.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T12 [get_ports led]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17 [get_ports sclk]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M19 [get_ports rst_n]
