set_property PACKAGE_PIN T12 [get_ports led]
set_property PACKAGE_PIN K17 [get_ports sclk]
set_property PACKAGE_PIN M19 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports sclk]
